version: '2'

services:
    postgres:
        image: postgres:alpine
        ports:
            - 54321:5432
        environment:
            - POSTGRES_DB=test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret

    mongo:
        image: mongo:latest
        ports:
            - 27017:27017


    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672